"""Adicionando campo is_active ao User

Revision ID: 2c84767650f6
Revises: 98d51966954f
Create Date: 2024-11-14 00:48:02.605522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c84767650f6'
down_revision = '98d51966954f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_user_email', ['email'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')  # Remover a constraint com o nome correto
        batch_op.alter_column('password',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('email')

    # ### end Alembic commands ###

